import { createContext, useContext, useState, useEffect, type ReactNode } from "react";

export type Language = "pl" | "en";

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "pl",
  setLang: () => {},
  t: (key: string) => key,
});

const translations: Record<string, Record<Language, string>> = {
  "nav.services": { pl: "Usługi", en: "Services" },
  "nav.portfolio": { pl: "Portfolio", en: "Portfolio" },
  "nav.process": { pl: "Proces", en: "Process" },
  "nav.contact": { pl: "Kontakt", en: "Contact" },
  "nav.login": { pl: "Zaloguj", en: "Login" },
  "nav.logout": { pl: "Wyloguj", en: "Logout" },
  "nav.panel": { pl: "Panel", en: "Panel" },
  "nav.myProfile": { pl: "Mój profil", en: "My profile" },
  "nav.startProject": { pl: "Rozpocznij projekt", en: "Start project" },
  "nav.projectQuote": { pl: "Wycena projektu", en: "Get a quote" },

  "hero.badge": { pl: "Nowoczesny Software House & Szkolenia IT", en: "Modern Software House & IT Training" },
  "hero.title1": { pl: "Budujemy aplikacje, które", en: "We build apps that" },
  "hero.title2": { pl: "skalują Twój biznes", en: "scale your business" },
  "hero.desc": { pl: "Tworzymy dedykowane systemy webowe, integracje AI oraz zaawansowane konfiguratory. Poznaj nasze możliwości w interaktywnym showroomie.", en: "We create custom web systems, AI integrations and advanced configurators. Explore our capabilities in the interactive showroom." },
  "hero.cta1": { pl: "Zobacz Realizacje & Demo", en: "See Projects & Demos" },
  "hero.cta2": { pl: "Wyślij Zapytanie", en: "Send Inquiry" },

  "about.title1": { pl: "Założony przez eksperta.", en: "Founded by an expert." },
  "about.title2": { pl: "Napędzany przez innowacje.", en: "Driven by innovation." },
  "about.desc": { pl: "Cześć, jestem Piotr Montewka – Architekt Oprogramowania i ekspert C++/Web. CodeMaster to efekt pasji do tworzenia niezawodnego kodu i dzielenia się wiedzą. Od zaawansowanych systemów po nowoczesne aplikacje webowe z AI – dostarczamy jakość bez kompromisów.", en: "Hi, I'm Piotr Montewka – Software Architect and C++/Web expert. CodeMaster is the result of passion for creating reliable code and sharing knowledge. From advanced systems to modern AI-powered web applications – we deliver quality without compromise." },
  "about.skill1": { pl: "C/C++, Python, Java", en: "C/C++, Python, Java" },
  "about.skill2": { pl: "Nowoczesny Web Dev", en: "Modern Web Dev" },
  "about.skill3": { pl: "AI Agents & LLMs", en: "AI Agents & LLMs" },
  "about.skill4": { pl: "Architektura Systemów", en: "Systems Architecture" },

  "services.title": { pl: "Co możemy dla Ciebie zbudować?", en: "What can we build for you?" },
  "services.desc": { pl: "Specjalizujemy się w pełnym cyklu życia oprogramowania, od koncepcji po wdrożenie i utrzymanie.", en: "We specialize in the full software lifecycle, from concept to deployment and maintenance." },
  "services.web": { pl: "Aplikacje Webowe", en: "Web Applications" },
  "services.webDesc": { pl: "Kompleksowe systemy SaaS, portale i panele B2B/B2C.", en: "Comprehensive SaaS systems, portals and B2B/B2C panels." },
  "services.desktop": { pl: "Aplikacje Desktopowe", en: "Desktop Applications" },
  "services.desktopDesc": { pl: "Wydajne rozwiązania w C++ i Java dla wymagających branż.", en: "High-performance C++ and Java solutions for demanding industries." },
  "services.backend": { pl: "Backend & API", en: "Backend & API" },
  "services.backendDesc": { pl: "Skalowalna architektura, bazy danych, mikroserwisy.", en: "Scalable architecture, databases, microservices." },
  "services.ai": { pl: "AI Agents", en: "AI Agents" },
  "services.aiDesc": { pl: "Inteligentne chatboty i automatyzacja procesów z użyciem LLM.", en: "Intelligent chatbots and process automation using LLMs." },
  "services.configurators": { pl: "Konfiguratory", en: "Configurators" },
  "services.configuratorsDesc": { pl: "Zaawansowane narzędzia do wycen i konfiguracji produktów 2D/3D.", en: "Advanced tools for quotes and 2D/3D product configuration." },
  "services.training": { pl: "Szkolenia IT", en: "IT Training" },
  "services.trainingDesc": { pl: "Mentoring i szkolenia z C++, Pythona, Web Dev dla firm i osób.", en: "Mentoring and training in C++, Python, Web Dev for companies and individuals." },
  "services.review": { pl: "Code Review", en: "Code Review" },
  "services.reviewDesc": { pl: "Audyty bezpieczeństwa i optymalizacja architektury oprogramowania.", en: "Security audits and software architecture optimization." },
  "services.devops": { pl: "DevOps & Integracje", en: "DevOps & Integrations" },
  "services.devopsDesc": { pl: "CI/CD, wdrożenia chmurowe, łączenie systemów zewnętrznych.", en: "CI/CD, cloud deployments, external system integrations." },

  "showroom.title": { pl: "Showroom Realizacji", en: "Project Showroom" },
  "showroom.desc": { pl: "Przetestuj działające demo naszych projektów. Od systemów rezerwacji po kreatory produktów.", en: "Test our working project demos. From booking systems to product configurators." },
  "showroom.viewAll": { pl: "Zobacz wszystkie 20 dem", en: "See all 20 demos" },
  "showroom.preparing": { pl: "Projekty w przygotowaniu", en: "Projects in preparation" },
  "showroom.preparingDesc": { pl: "Odwiedź nas wkrótce, aby zobaczyć najnowsze demo.", en: "Visit us soon to see the latest demos." },

  "process.title": { pl: "Jak współpracujemy?", en: "How do we work together?" },
  "process.step1": { pl: "Brief & Analiza", en: "Brief & Analysis" },
  "process.step1Desc": { pl: "Zrozumienie Twoich potrzeb i celów biznesowych.", en: "Understanding your needs and business goals." },
  "process.step2": { pl: "Architektura", en: "Architecture" },
  "process.step2Desc": { pl: "Projektowanie skalowalnego rozwiązania i UX/UI.", en: "Designing a scalable solution and UX/UI." },
  "process.step3": { pl: "Implementacja", en: "Implementation" },
  "process.step3Desc": { pl: "Zwinne programowanie z regularnymi demonstracjami.", en: "Agile development with regular demonstrations." },
  "process.step4": { pl: "Testy & QA", en: "Testing & QA" },
  "process.step4Desc": { pl: "Audyty, testy automatyczne i manualne.", en: "Audits, automated and manual testing." },
  "process.step5": { pl: "Wdrożenie", en: "Deployment" },
  "process.step5Desc": { pl: "Bezpieczny deploy na produkcję.", en: "Safe production deployment." },
  "process.step6": { pl: "Rozwój", en: "Growth" },
  "process.step6Desc": { pl: "Utrzymanie SLA i budowa nowych modułów.", en: "SLA maintenance and building new modules." },

  "contact.title": { pl: "Porozmawiajmy o Twoim projekcie", en: "Let's talk about your project" },
  "contact.desc": { pl: "Zostaw nam szczegóły, a my przygotujemy bezpłatną wycenę i propozycję architektury.", en: "Leave us the details and we'll prepare a free quote and architecture proposal." },
  "contact.writeDirect": { pl: "Napisz bezpośrednio", en: "Write directly" },
  "contact.callUs": { pl: "Zadzwoń do nas", en: "Call us" },
  "contact.bookDemo": { pl: "Umów się na demo", en: "Book a demo" },
  "contact.videoCall": { pl: "Wideorozmowa Google Meet", en: "Google Meet video call" },
  "contact.name": { pl: "Imię i nazwisko", en: "Full name" },
  "contact.email": { pl: "E-mail", en: "Email" },
  "contact.phone": { pl: "Telefon", en: "Phone" },
  "contact.company": { pl: "Firma", en: "Company" },
  "contact.projectType": { pl: "Rodzaj projektu", en: "Project type" },
  "contact.budget": { pl: "Budżet (orientacyjny)", en: "Budget (approximate)" },
  "contact.deadline": { pl: "Termin realizacji", en: "Deadline" },
  "contact.projectDesc": { pl: "Opis projektu", en: "Project description" },
  "contact.projectDescPlaceholder": { pl: "Opisz w kilku słowach co chcesz osiągnąć...", en: "Describe in a few words what you want to achieve..." },
  "contact.consentContact": { pl: "Wyrażam zgodę na przetwarzanie moich danych osobowych w celu odpowiedzi na zapytanie.*", en: "I consent to the processing of my personal data to respond to this inquiry.*" },
  "contact.consentPrivacy": { pl: "Akceptuję Politykę Prywatności.*", en: "I accept the Privacy Policy.*" },
  "contact.submit": { pl: "Wyślij zapytanie", en: "Send inquiry" },
  "contact.success": { pl: "Sukces!", en: "Success!" },
  "contact.successDesc": { pl: "Twoje zapytanie zostało wysłane. Skontaktujemy się wkrótce.", en: "Your inquiry has been sent. We'll contact you soon." },
  "contact.error": { pl: "Błąd", en: "Error" },
  "contact.errorDesc": { pl: "Wystąpił problem podczas wysyłania. Spróbuj ponownie.", en: "There was a problem sending. Please try again." },
  "contact.choose": { pl: "Wybierz...", en: "Choose..." },
  "contact.typeWeb": { pl: "Aplikacja Webowa / SaaS", en: "Web App / SaaS" },
  "contact.typeEcommerce": { pl: "E-commerce / Konfigurator", en: "E-commerce / Configurator" },
  "contact.typeAi": { pl: "Integracja AI / Chatbot", en: "AI Integration / Chatbot" },
  "contact.typeDesktop": { pl: "Aplikacja Desktopowa", en: "Desktop Application" },
  "contact.typeTraining": { pl: "Szkolenie / Mentoring", en: "Training / Mentoring" },
  "contact.typeOther": { pl: "Inne", en: "Other" },
  "contact.budgetSmall": { pl: "do 10 000 PLN", en: "up to 10,000 PLN" },
  "contact.budgetMedium": { pl: "10 000 - 30 000 PLN", en: "10,000 - 30,000 PLN" },
  "contact.budgetLarge": { pl: "30 000 - 100 000 PLN", en: "30,000 - 100,000 PLN" },
  "contact.budgetEnterprise": { pl: "powyżej 100 000 PLN", en: "above 100,000 PLN" },
  "contact.budgetUndefined": { pl: "Do ustalenia", en: "To be determined" },
  "contact.deadlineAsap": { pl: "Jak najszybciej", en: "ASAP" },
  "contact.deadline1m": { pl: "W ciągu 1 miesiąca", en: "Within 1 month" },
  "contact.deadline3m": { pl: "W ciągu 3 miesięcy", en: "Within 3 months" },
  "contact.deadline6m": { pl: "W ciągu 6 miesięcy", en: "Within 6 months" },
  "contact.deadlineFlexible": { pl: "Elastyczny", en: "Flexible" },

  "faq.title": { pl: "Często zadawane pytania", en: "Frequently Asked Questions" },
  "faq.q1": { pl: "Ile kosztuje stworzenie aplikacji webowej?", en: "How much does it cost to build a web application?" },
  "faq.a1": { pl: "Koszt zależy od złożoności projektu, liczby integracji i wybranego stosu technologicznego. Proste panele zaczynają się od kilkunastu tysięcy złotych, podczas gdy zaawansowane systemy SaaS mogą wymagać większego budżetu. Zawsze zaczynamy od bezpłatnej wyceny po poznaniu wymagań.", en: "The cost depends on project complexity, number of integrations and chosen tech stack. Simple panels start from several thousand PLN, while advanced SaaS systems may require a larger budget. We always start with a free quote after understanding your requirements." },
  "faq.q2": { pl: "Jak długo trwa realizacja projektu?", en: "How long does project development take?" },
  "faq.a2": { pl: "MVP (Minimum Viable Product) jesteśmy w stanie dowieźć zazwyczaj w 1-3 miesiące. Rozbudowane systemy enterprise wymagają dłuższego czasu, ale pracujemy w sprintach, dostarczając działające moduły co 2 tygodnie.", en: "We can typically deliver an MVP in 1-3 months. Complex enterprise systems take longer, but we work in sprints, delivering working modules every 2 weeks." },
  "faq.q3": { pl: "Czy oferujecie utrzymanie po wdrożeniu?", en: "Do you offer maintenance after deployment?" },
  "faq.a3": { pl: "Tak, oferujemy pakiety SLA obejmujące utrzymanie serwerów, aktualizacje bezpieczeństwa, monitoring oraz pule godzin na rozwój nowych funkcji.", en: "Yes, we offer SLA packages including server maintenance, security updates, monitoring and hour pools for new feature development." },
  "faq.q4": { pl: "W jakich technologiach pracujecie?", en: "What technologies do you work with?" },
  "faq.a4": { pl: "Frontend: React, Vue, TypeScript, Tailwind. Backend: Node.js, Python, Java, C++. Bazy danych: PostgreSQL, Redis. DevOps: Docker, AWS, CI/CD. AI: OpenAI API, LangChain.", en: "Frontend: React, Vue, TypeScript, Tailwind. Backend: Node.js, Python, Java, C++. Databases: PostgreSQL, Redis. DevOps: Docker, AWS, CI/CD. AI: OpenAI API, LangChain." },
  "faq.q5": { pl: "Czy mogę zobaczyć demo przed rozpoczęciem współpracy?", en: "Can I see demos before starting collaboration?" },
  "faq.a5": { pl: "Zdecydowanie! Nasz showroom zawiera 20 gotowych projektów demonstracyjnych z różnych branż (rezerwacje, e-commerce, AI). Możesz je przetestować za darmo.", en: "Absolutely! Our showroom contains 20 ready demo projects from various industries (booking, e-commerce, AI). You can test them for free." },

  "portfolio.title": { pl: "Showroom", en: "Showroom" },
  "portfolio.titleAccent": { pl: "Projektów", en: "of Projects" },
  "portfolio.desc": { pl: "Przejrzyj nasze gotowe moduły, realizacje i koncepty. Uruchom demo, aby na żywo sprawdzić możliwości naszych systemów.", en: "Browse our ready modules, projects and concepts. Run demos to see our systems' capabilities live." },
  "portfolio.all": { pl: "Wszystkie", en: "All" },
  "portfolio.search": { pl: "Szukaj projektu...", en: "Search project..." },
  "portfolio.noResults": { pl: "Brak wyników", en: "No results" },
  "portfolio.noResultsDesc": { pl: "Nie znaleźliśmy projektów pasujących do kryteriów.", en: "We couldn't find projects matching the criteria." },

  "project.back": { pl: "Wróć do listy", en: "Back to list" },
  "project.runDemo": { pl: "Uruchom Demo", en: "Run Demo" },
  "project.runApp": { pl: "Uruchom Aplikację", en: "Run Application" },
  "project.saveFav": { pl: "Zapisz do ulubionych", en: "Save to favorites" },
  "project.features": { pl: "Kluczowe funkcjonalności", en: "Key Features" },
  "project.techStack": { pl: "Stos Technologiczny", en: "Tech Stack" },
  "project.wantSimilar": { pl: "Chcesz podobny system?", en: "Want a similar system?" },
  "project.wantSimilarDesc": { pl: "Możemy dostosować to rozwiązanie do potrzeb Twojego biznesu lub zbudować coś od zera.", en: "We can customize this solution to your business needs or build something from scratch." },
  "project.askQuote": { pl: "Zapytaj o wycenę", en: "Ask for a quote" },
  "project.notFound": { pl: "Projekt nie znaleziony", en: "Project not found" },
  "project.backToPortfolio": { pl: "Wróć do portfolio", en: "Back to portfolio" },
  "project.loginToFav": { pl: "Zaloguj się", en: "Log in" },
  "project.loginToFavDesc": { pl: "Musisz być zalogowany by dodać do ulubionych", en: "You must be logged in to add favorites" },
  "project.addedToFav": { pl: "Dodano do ulubionych", en: "Added to favorites" },
  "project.removedFromFav": { pl: "Usunięto z ulubionych", en: "Removed from favorites" },
  "project.preview": { pl: "Podgląd Demo", en: "Demo Preview" },
  "project.screenshots": { pl: "Zrzuty ekranów", en: "Screenshots" },

  "dashboard.loginRequired": { pl: "Wymagane logowanie", en: "Login required" },
  "dashboard.loginDesc": { pl: "Zaloguj się, aby uzyskać dostęp do swojego panelu, ulubionych projektów i historii zapytań.", en: "Log in to access your panel, favorite projects and inquiry history." },
  "dashboard.loginGoogle": { pl: "Zaloguj przez Google", en: "Login with Google" },
  "dashboard.logout": { pl: "Wyloguj", en: "Logout" },
  "dashboard.myInquiries": { pl: "Moje Zapytania", en: "My Inquiries" },
  "dashboard.favDemos": { pl: "Ulubione Demo", en: "Favorite Demos" },
  "dashboard.noInquiries": { pl: "Nie masz jeszcze żadnych zapytań.", en: "You don't have any inquiries yet." },
  "dashboard.startProject": { pl: "Rozpocznij projekt", en: "Start a project" },
  "dashboard.noFavorites": { pl: "Nie dodałeś jeszcze żadnych projektów do ulubionych.", en: "You haven't added any projects to favorites yet." },
  "dashboard.browseShowroom": { pl: "Przeglądaj Showroom", en: "Browse Showroom" },
  "dashboard.sentOn": { pl: "Wysłano", en: "Sent on" },
  "dashboard.statusNew": { pl: "Nowe", en: "New" },
  "dashboard.statusProgress": { pl: "Analiza", en: "In Progress" },
  "dashboard.statusQuoted": { pl: "Wycenione", en: "Quoted" },
  "dashboard.statusWon": { pl: "Realizacja", en: "In Development" },
  "dashboard.statusLost": { pl: "Odrzucone", en: "Rejected" },

  "footer.desc": { pl: "Tworzymy dedykowane oprogramowanie, aplikacje webowe oraz inteligentne systemy AI dla biznesu. Skalujemy Twój sukces przez technologię.", en: "We create custom software, web applications and intelligent AI systems for business. We scale your success through technology." },
  "footer.quickLinks": { pl: "Szybkie linki", en: "Quick Links" },
  "footer.ourServices": { pl: "Nasze Usługi", en: "Our Services" },
  "footer.portfolioDemos": { pl: "Portfolio & Demo", en: "Portfolio & Demos" },
  "footer.processColab": { pl: "Proces Współpracy", en: "Collaboration Process" },
  "footer.servicesTitle": { pl: "Usługi", en: "Services" },
  "footer.webApps": { pl: "Aplikacje Webowe", en: "Web Applications" },
  "footer.aiAgents": { pl: "Systemy AI & Agenci", en: "AI Systems & Agents" },
  "footer.configurators": { pl: "Konfiguratory 3D/2D", en: "3D/2D Configurators" },
  "footer.trainingMentoring": { pl: "Szkolenia & Mentoring", en: "Training & Mentoring" },
  "footer.contactTitle": { pl: "Kontakt", en: "Contact" },
  "footer.location": { pl: "Polska, Zdalnie (Cały świat)", en: "Poland, Remote (Worldwide)" },
  "footer.copyright": { pl: "CodeMaster Piotr Montewka. Wszelkie prawa zastrzeżone.", en: "CodeMaster Piotr Montewka. All rights reserved." },
  "footer.privacy": { pl: "Polityka Prywatności", en: "Privacy Policy" },
  "footer.terms": { pl: "Regulamin", en: "Terms of Service" },

  "theme.dark": { pl: "Ciemny", en: "Dark" },
  "theme.light": { pl: "Jasny", en: "Light" },
  "theme.grey": { pl: "Szary", en: "Grey" },

  "ai.greeting": { pl: "Cześć! Jestem asystentem AI CodeMaster. W czym mogę pomóc? Opowiedz mi o swoim pomyśle na projekt.", en: "Hi! I'm the CodeMaster AI assistant. How can I help? Tell me about your project idea." },
  "ai.title": { pl: "CodeMaster AI", en: "CodeMaster AI" },
  "ai.active": { pl: "Aktywny", en: "Active" },
  "ai.analyzing": { pl: "AI analizuje...", en: "AI analyzing..." },
  "ai.placeholder": { pl: "Napisz wiadomość...", en: "Type a message..." },
  "ai.error": { pl: "Przepraszam, wystąpił błąd w komunikacji. Spróbuj ponownie za chwilę.", en: "Sorry, a communication error occurred. Please try again in a moment." },

  "demo.march2026": { pl: "Marzec 2026", en: "March 2026" },
  "demo.availableHours": { pl: "Dostępne godziny:", en: "Available hours:" },
  "demo.bookSlot": { pl: "Zarezerwuj termin", en: "Book appointment" },
  "demo.all": { pl: "Wszystkie", en: "All" },
  "demo.popular": { pl: "Popularne", en: "Popular" },
  "demo.new": { pl: "Nowe", en: "New" },
  "demo.sales": { pl: "Promocje", en: "Sales" },
  "demo.addToCart": { pl: "+ Koszyk", en: "+ Cart" },
  "demo.width": { pl: "Szerokość", en: "Width" },
  "demo.height": { pl: "Wysokość", en: "Height" },
  "demo.color": { pl: "Kolor", en: "Color" },
  "demo.estimatedPrice": { pl: "Szacunkowa cena:", en: "Estimated price:" },
  "demo.clients": { pl: "Klienci", en: "Clients" },
  "demo.revenue": { pl: "Przychody", en: "Revenue" },
  "demo.documents": { pl: "Dokumenty", en: "Documents" },
  "demo.messages": { pl: "Wiadomości", en: "Messages" },
  "demo.activity30d": { pl: "Aktywność (30 dni)", en: "Activity (30 days)" },
  "demo.yourProgress": { pl: "Twój postęp", en: "Your progress" },
  "demo.coursesInProgress": { pl: "3 kursy w trakcie • 42% ukończone", en: "3 courses in progress • 42% completed" },
  "demo.lessons": { pl: "lekcji", en: "lessons" },
  "demo.advanced": { pl: "Zaawansowany", en: "Advanced" },
  "demo.intermediate": { pl: "Średni", en: "Intermediate" },
  "demo.beginner": { pl: "Podstawowy", en: "Beginner" },
  "demo.aiGreeting": { pl: "Witaj! Jestem Twoim asystentem AI. Jak mogę Ci pomóc?", en: "Hi! I'm your AI assistant. How can I help?" },
  "demo.aiUserMsg": { pl: "Potrzebuję wyceny systemu rezerwacji online.", en: "I need a quote for an online booking system." },
  "demo.aiReply": { pl: "Chętnie pomogę! System rezerwacji online zazwyczaj obejmuje: kalendarz, zarządzanie usługami, powiadomienia email/SMS, panel admina. Szacunkowy koszt to 15-35K PLN. Chcesz omówić szczegóły?", en: "I'd be happy to help! An online booking system typically includes: calendar, service management, email/SMS notifications, admin panel. Estimated cost is 15-35K PLN. Would you like to discuss details?" },
  "demo.writeMessage": { pl: "Napisz wiadomość...", en: "Type a message..." },
  "demo.projectQuote": { pl: "Wycena projektu", en: "Project quote" },
  "demo.availableTech": { pl: "Dostępne technologie", en: "Available technologies" },
  "demo.timeline": { pl: "Czas realizacji", en: "Timeline" },
  "demo.portfolio": { pl: "Portfolio", en: "Portfolio" },
  "demo.online": { pl: "Online", en: "Online" },

  "cookie.title": { pl: "Pliki cookies", en: "Cookies" },
  "cookie.desc": { pl: "Ta strona wykorzystuje pliki cookies do zapewnienia prawidłowego działania serwisu, utrzymania sesji logowania oraz poprawy doświadczenia użytkownika. Więcej informacji w naszej", en: "This website uses cookies to ensure proper functionality, maintain login sessions, and improve user experience. More information in our" },
  "cookie.accept": { pl: "Akceptuję", en: "Accept" },
  "cookie.decline": { pl: "Odrzucam", en: "Decline" },

  "admin.title": { pl: "Panel Administratora", en: "Admin Panel" },
  "admin.noAccess": { pl: "Brak Dostępu", en: "Access Denied" },
  "admin.noAccessDesc": { pl: "Panel dostępny tylko dla administratorów.", en: "This panel is only available to administrators." },
  "admin.projects": { pl: "Projekty (Showroom)", en: "Projects (Showroom)" },
  "admin.leads": { pl: "Leady (Zapytania)", en: "Leads (Inquiries)" },
  "admin.users": { pl: "Użytkownicy", en: "Users" },
  "admin.settings": { pl: "Ustawienia", en: "Settings" },
  "admin.manageProjects": { pl: "Zarządzanie Projektami", en: "Project Management" },
  "admin.addProject": { pl: "Dodaj Projekt", en: "Add Project" },
  "admin.editProject": { pl: "Edytuj Projekt", en: "Edit Project" },
  "admin.newProject": { pl: "Nowy Projekt", en: "New Project" },
  "admin.name": { pl: "Nazwa", en: "Name" },
  "admin.category": { pl: "Kategoria", en: "Category" },
  "admin.industry": { pl: "Branża", en: "Industry" },
  "admin.status": { pl: "Status", en: "Status" },
  "admin.actions": { pl: "Akcje", en: "Actions" },
  "admin.save": { pl: "Zapisz", en: "Save" },
  "admin.cancel": { pl: "Anuluj", en: "Cancel" },
  "admin.description": { pl: "Opis", en: "Description" },
  "admin.features": { pl: "Funkcjonalności (po przecinku)", en: "Features (comma-separated)" },
  "admin.technologies": { pl: "Technologie (po przecinku)", en: "Technologies (comma-separated)" },
  "admin.thumbnailUrl": { pl: "URL miniaturki (opcjonalne)", en: "Thumbnail URL (optional)" },
  "admin.demoUrl": { pl: "URL dema (opcjonalne)", en: "Demo URL (optional)" },
  "admin.deleted": { pl: "Usunięto projekt", en: "Project deleted" },
  "admin.created": { pl: "Projekt utworzony", en: "Project created" },
  "admin.updated": { pl: "Projekt zaktualizowany", en: "Project updated" },
  "admin.statusUpdated": { pl: "Status zaktualizowany", en: "Status updated" },
  "admin.roleUpdated": { pl: "Rola zaktualizowana", en: "Role updated" },
  "admin.leadsTitle": { pl: "Leady & Zapytania", en: "Leads & Inquiries" },
  "admin.date": { pl: "Data", en: "Date" },
  "admin.client": { pl: "Klient", en: "Client" },
  "admin.type": { pl: "Typ", en: "Type" },
  "admin.usersTitle": { pl: "Użytkownicy Systemu", en: "System Users" },
  "admin.user": { pl: "Użytkownik", en: "User" },
  "admin.email": { pl: "Email", en: "Email" },
  "admin.registration": { pl: "Rejestracja", en: "Registration" },
  "admin.role": { pl: "Rola", en: "Role" },
  "admin.notes": { pl: "Notatki", en: "Notes" },
  "admin.priority": { pl: "Priorytet", en: "Priority" },
  "admin.confirmDelete": { pl: "Na pewno usunąć?", en: "Are you sure you want to delete?" },
  "admin.leadDescription": { pl: "Opis zapytania", en: "Inquiry description" },
  "admin.budget": { pl: "Budżet", en: "Budget" },
  "admin.deadline": { pl: "Termin", en: "Deadline" },

  "seo.homeTitle": { pl: "CodeMaster - AI & Software Solutions | Piotr Montewka", en: "CodeMaster - AI & Software Solutions | Piotr Montewka" },
  "seo.homeDesc": { pl: "Profesjonalne tworzenie aplikacji webowych, integracje AI, konfiguratory 3D i szkolenia IT. 20 interaktywnych dem projektów. Software House Piotr Montewka.", en: "Professional web application development, AI integrations, 3D configurators and IT training. 20 interactive project demos. Software House by Piotr Montewka." },
  "seo.portfolioTitle": { pl: "Showroom Projektów | CodeMaster", en: "Project Showroom | CodeMaster" },
  "seo.portfolioDesc": { pl: "Przejrzyj 20 gotowych projektów demo - od systemów rezerwacji po konfiguratory i asystentów AI. Przetestuj na żywo!", en: "Browse 20 ready demo projects - from booking systems to configurators and AI assistants. Test them live!" },
  "seo.dashboardTitle": { pl: "Panel Użytkownika | CodeMaster", en: "User Dashboard | CodeMaster" },
  "seo.privacyTitle": { pl: "Polityka Prywatności | CodeMaster", en: "Privacy Policy | CodeMaster" },
  "seo.termsTitle": { pl: "Regulamin | CodeMaster", en: "Terms of Service | CodeMaster" },

  "dashboard.editProfile": { pl: "Edytuj profil", en: "Edit profile" },
  "dashboard.deleteAccount": { pl: "Usuń konto", en: "Delete account" },
  "dashboard.deleteAccountConfirm": { pl: "Czy na pewno chcesz usunąć swoje konto? Ta operacja jest nieodwracalna.", en: "Are you sure you want to delete your account? This action is irreversible." },
  "dashboard.deleteAccountSuccess": { pl: "Konto zostało usunięte", en: "Account has been deleted" },
  "dashboard.profileUpdated": { pl: "Profil zaktualizowany", en: "Profile updated" },
  "dashboard.firstName": { pl: "Imię", en: "First name" },
  "dashboard.lastName": { pl: "Nazwisko", en: "Last name" },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      return (localStorage.getItem("cm-lang") as Language) || "pl";
    }
    return "pl";
  });

  useEffect(() => {
    localStorage.setItem("cm-lang", lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key: string): string => {
    return translations[key]?.[lang] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
