import { db, projectsTable } from "@workspace/db";

const DEMO_PROJECTS = [
  {
    id: "bda93603-733d-4261-8797-ddf47e35e896",
    name: "Salon Kosmetyczny — Rezerwacje Online",
    category: "Booking",
    industry: "Beauty",
    description: "Kompleksowy system rezerwacji online dla salonu kosmetycznego. Klient może samodzielnie rezerwować wizyty, wybierać usługi i stylizacje, a właściciel zarządza kalendarzem i personelem.",
    features: ["Kalendarz rezerwacji online", "Zarządzanie usługami i cenami", "Panel klienta z historią wizyt", "Powiadomienia SMS/email", "Moduł lojalnościowy"],
    status: "demo" as const,
    featured: true,
    thumbnailUrl: null,
    demoUrl: null,
    technologies: ["React", "Node.js", "PostgreSQL", "SMS API"],
    sortOrder: "01",
  },
  {
    id: "12b6fd69-1ae9-431f-926d-824067fb8552",
    name: "Barber/Fryzjer — Kalendarz Wizyt",
    category: "Booking",
    industry: "Beauty",
    description: "Aplikacja do zarządzania wizytami w barberze. Stylowy interfejs z możliwością wyboru barbera, rodzaju usługi oraz preferowanego terminu.",
    features: ["Wybór barbera i usługi", "Kalendarz interaktywny", "Historia wizyt", "Galeria prac", "Oceny i recenzje"],
    status: "demo" as const,
    featured: false,
    thumbnailUrl: null,
    demoUrl: null,
    technologies: ["React", "Express", "Calendar API"],
    sortOrder: "02",
  },
  {
    id: "98663b60-d306-486a-b5f0-31f79c7a2db2",
    name: "Restauracja — Menu i Zamówienia Online",
    category: "E-commerce",
    industry: "Food",
    description: "Cyfrowe menu restauracji z możliwością składania zamówień online. System obsługuje zamówienia na miejscu, na wynos i z dostawą.",
    features: ["Cyfrowe menu z kategoriami", "Koszyk zakupów", "Zamówienia na wynos / dostawa", "Panel kuchni", "Moduł recenzji"],
    status: "demo" as const,
    featured: false,
    thumbnailUrl: null,
    demoUrl: null,
    technologies: ["React", "Node.js", "Stripe", "Socket.io"],
    sortOrder: "03",
  },
  {
    id: "8457904a-5c1a-452b-9518-2e0ce5707884",
    name: "Hotel/Apartamenty — System Rezerwacji",
    category: "Booking",
    industry: "Hospitality",
    description: "Profesjonalny system rezerwacji dla hoteli i apartamentów. Pełne zarządzanie dostępnością pokoi, cenami sezonowymi i obsługą gości.",
    features: ["Wyszukiwarka pokoi z filtrami", "Rezerwacja z płatnością online", "Panel gościa", "Zarządzanie dostępnością", "Channel manager"],
    status: "demo" as const,
    featured: false,
    thumbnailUrl: null,
    demoUrl: null,
    technologies: ["React", "Node.js", "Stripe", "PostgreSQL"],
    sortOrder: "04",
  },
  {
    id: "44c49fbc-29b1-4081-a8f6-6dcbcfdce91c",
    name: "Klinika Medyczna — Panel Pacjenta",
    category: "Healthcare",
    industry: "Medical",
    description: "Nowoczesny panel pacjenta dla kliniki medycznej. Rejestracja wizyt online, dostęp do wyników badań i historia leczenia w jednym miejscu.",
    features: ["Rejestracja wizyt online", "Wyniki badań online", "Historia wizyt i recept", "Teleporada wideo", "Przypomnienia o wizytach"],
    status: "demo" as const,
    featured: true,
    thumbnailUrl: null,
    demoUrl: null,
    technologies: ["React", "Node.js", "PostgreSQL", "WebRTC"],
    sortOrder: "05",
  },
  {
    id: "c2dcd3d7-e54b-4d1f-b5dc-d9424ec82d84",
    name: "Siłownia/Fitness — Membership i Grafik",
    category: "Booking",
    industry: "Fitness",
    description: "Platforma dla siłowni i klubów fitness. Zarządzanie karnetami, rezerwacja zajęć grupowych i śledzenie postępów treningowych.",
    features: ["Zarządzanie karnetami", "Rezerwacja zajęć grupowych", "Grafik zajęć", "Dziennik treningów", "Panel instruktora"],
    status: "demo" as const,
    featured: false,
    thumbnailUrl: null,
    demoUrl: null,
    technologies: ["React", "Node.js", "PostgreSQL", "Stripe"],
    sortOrder: "06",
  },
  {
    id: "b8c1dd6f-e1ea-424e-87ef-9d633af63c7f",
    name: "Sklep Meblowy — Konfigurator Szafy",
    category: "Configurator",
    industry: "Furniture",
    description: "Interaktywny konfigurator szafy dla sklepu meblowego. Klient projektuje szafę w 3D, wybierając wymiary, front, kolorystykę i wyposażenie wnętrza.",
    features: ["Konfigurator 3D w czasie rzeczywistym", "Wybór materiałów i kolorów", "Kalkulator ceny", "Eksport do PDF", "Zamówienie z poziomu konfiguratora"],
    status: "demo" as const,
    featured: true,
    thumbnailUrl: null,
    demoUrl: null,
    technologies: ["React", "Three.js", "Node.js", "PostgreSQL"],
    sortOrder: "07",
  },
  {
    id: "2af6b310-1336-41e1-aed3-e8534c28d42b",
    name: "Kuchnie na Wymiar — Konfigurator Projektu",
    category: "Configurator",
    industry: "Kitchen",
    description: "Konfigurator mebli kuchennych na wymiar. Projektuj kuchnię marzeń dobierając layout, fronty, blaty, sprzęt AGD i kolorystykę.",
    features: ["Wizard konfiguracji krok po kroku", "Podgląd wizualizacji", "Dobór sprzętu AGD", "Wycena automatyczna", "Formularz zapytania"],
    status: "demo" as const,
    featured: false,
    thumbnailUrl: null,
    demoUrl: null,
    technologies: ["React", "Canvas API", "Node.js"],
    sortOrder: "08",
  },
  {
    id: "80766e19-ca73-4181-a379-a76e10637c1a",
    name: "Deweloper Nieruchomości — Katalog Inwestycji",
    category: "Real Estate",
    industry: "Construction",
    description: "Interaktywny katalog inwestycji deweloperskich. Przeglądaj dostępne lokale, filtruj po parametrach i umów się na prezentację.",
    features: ["Interaktywna mapa inwestycji", "Filtrowanie lokali wg parametrów", "Wizualizacje 3D", "Formularz zapytania", "Panel klienta"],
    status: "demo" as const,
    featured: false,
    thumbnailUrl: null,
    demoUrl: null,
    technologies: ["React", "Mapbox", "Node.js", "PostgreSQL"],
    sortOrder: "09",
  },
  {
    id: "915c9062-9302-4f47-8da2-92ec78c51ae6",
    name: "Biuro Rachunkowe — Panel Klienta",
    category: "Client Portal",
    industry: "Finance",
    description: "Bezpieczny panel klienta dla biura rachunkowego. Bezproblemowa wymiana dokumentów, komunikacja i dostęp do raportów finansowych.",
    features: ["Wymiana dokumentów online", "Statusy rozliczeń", "Komunikator z księgowym", "Archiwum dokumentów", "Eksport raportów"],
    status: "demo" as const,
    featured: false,
    thumbnailUrl: null,
    demoUrl: null,
    technologies: ["React", "Node.js", "PostgreSQL", "AWS S3"],
    sortOrder: "10",
  },
  {
    id: "487c9fbe-cc36-48ad-8fd7-da90feca87c3",
    name: "Kancelaria Prawna — Leady i Konsultacje",
    category: "Lead Management",
    industry: "Legal",
    description: "System zarządzania leadami i konsultacjami dla kancelarii prawnej. Przyjmuj zgłoszenia, kwalifikuj klientów i zarządzaj sprawami.",
    features: ["Formularz zgłoszenia sprawy", "Kwalifikacja leadów", "Panel spraw i dokumentów", "Komunikacja z klientem", "Fakturowanie"],
    status: "demo" as const,
    featured: false,
    thumbnailUrl: null,
    demoUrl: null,
    technologies: ["React", "Node.js", "PostgreSQL"],
    sortOrder: "11",
  },
  {
    id: "84dd93ad-914e-482a-8189-9180cfabe0d9",
    name: "Agencja Marketingowa — Panel Raportów",
    category: "Dashboard",
    industry: "Marketing",
    description: "Dashboard raportów marketingowych dla agencji. Wizualizuj wyniki kampanii, śledź KPIs i przygotowuj raporty dla klientów automatycznie.",
    features: ["Dashboard KPIs w czasie rzeczywistym", "Integracje z Google/Meta Ads", "Automatyczne raporty", "Porównanie kampanii", "Alerty i powiadomienia"],
    status: "demo" as const,
    featured: false,
    thumbnailUrl: null,
    demoUrl: null,
    technologies: ["React", "Recharts", "Node.js", "Google API"],
    sortOrder: "12",
  },
  {
    id: "af2ec9fe-950b-4419-bd30-2cb14d561cf6",
    name: "Szkoła Online — Kursy i Konto",
    category: "E-learning",
    industry: "Education",
    description: "Platforma e-learningowa dla szkół i kursów online. Sprzedawaj kursy, prowadź lekcje wideo i śledź postępy uczniów.",
    features: ["Kursy wideo z quizami", "Certyfikaty ukończenia", "Forum dyskusyjne", "Panel postępów", "Płatności Stripe"],
    status: "demo" as const,
    featured: false,
    thumbnailUrl: null,
    demoUrl: null,
    technologies: ["React", "Node.js", "PostgreSQL", "Stripe", "AWS S3"],
    sortOrder: "13",
  },
  {
    id: "d6752d43-a02f-4a12-b7bf-de14ea657334",
    name: "E-learning/Mentoring — Strefa Premium",
    category: "E-learning",
    industry: "Education",
    description: "Platforma mentoringowa ze strefą premium. Rezerwuj sesje 1:1 z mentorem, korzystaj z ekskluzywnych materiałów i społeczności.",
    features: ["Rezerwacja sesji mentoringowych", "Strefa premium z materiałami", "Społeczność zamknięta", "Śledzenie postępów", "Integracja z Calendly"],
    status: "demo" as const,
    featured: false,
    thumbnailUrl: null,
    demoUrl: null,
    technologies: ["React", "Node.js", "PostgreSQL", "Stripe"],
    sortOrder: "14",
  },
  {
    id: "de20e83d-4309-429b-9663-7b439d97ea63",
    name: "Portal Eventowy — Bilety i Harmonogram",
    category: "Events",
    industry: "Entertainment",
    description: "Platforma sprzedaży biletów i zarządzania harmonogramem wydarzeń. Organizuj konferencje, koncerty i warsztaty z pełną obsługą uczestników.",
    features: ["Sprzedaż biletów online", "Kody QR do wejścia", "Harmonogram prelegentów", "Mapa miejsca", "Aplikacja mobilna dla uczestników"],
    status: "demo" as const,
    featured: false,
    thumbnailUrl: null,
    demoUrl: null,
    technologies: ["React", "Node.js", "Stripe", "QR Code API"],
    sortOrder: "15",
  },
  {
    id: "0d0674f8-8dcb-409c-9101-c5e936aa80dc",
    name: "Wypożyczalnia Aut — Rezerwacje i Flota",
    category: "Booking",
    industry: "Automotive",
    description: "System zarządzania flotą i rezerwacjami dla wypożyczalni samochodów. Pełna obsługa klienta od rezerwacji po zwrot pojazdu.",
    features: ["Katalog pojazdów z filtrowaniem", "Rezerwacja online z płatnością", "Zarządzanie flotą", "Umowy online", "Panel kierowcy"],
    status: "demo" as const,
    featured: false,
    thumbnailUrl: null,
    demoUrl: null,
    technologies: ["React", "Node.js", "PostgreSQL", "Stripe"],
    sortOrder: "16",
  },
  {
    id: "293bf3d5-72c8-4ad0-855b-feb9536a4ca4",
    name: "Serwis Komputerowy — Zgłoszenia Napraw",
    category: "Service Management",
    industry: "IT",
    description: "System obsługi zgłoszeń serwisowych dla serwisu komputerowego. Klient śledzi status naprawy online, a technik zarządza zleceniami.",
    features: ["Formularz zgłoszenia usterki", "Śledzenie statusu naprawy", "Wycena online", "Historia napraw", "Panel technika"],
    status: "demo" as const,
    featured: false,
    thumbnailUrl: null,
    demoUrl: null,
    technologies: ["React", "Node.js", "PostgreSQL", "SMS API"],
    sortOrder: "17",
  },
  {
    id: "462b7b8f-a92b-4e60-abb8-0a9b33498760",
    name: "Firma Budowlana — Kalkulator Wyceny",
    category: "Calculator",
    industry: "Construction",
    description: "Interaktywny kalkulator wyceny prac budowlanych. Klient sam konfiguruje zakres prac i otrzymuje szacunkową wycenę natychmiast.",
    features: ["Kalkulator robocizny i materiałów", "Konfigurator zakresu prac", "Wycena w czasie rzeczywistym", "Eksport do PDF", "Formularz zapytania"],
    status: "demo" as const,
    featured: false,
    thumbnailUrl: null,
    demoUrl: null,
    technologies: ["React", "Node.js", "PDF Generator"],
    sortOrder: "18",
  },
  {
    id: "7744c26e-a07c-4c28-b0c0-a2cb0ca3df3b",
    name: "E-commerce Premium — Landing i Checkout",
    category: "E-commerce",
    industry: "Retail",
    description: "Premium sklep e-commerce z dopracowanym landing page i procesem zakupowym. Maksymalna konwersja dzięki UX opartemu na danych.",
    features: ["Landing page sprzedażowy", "Koszyk z upsell", "Checkout jednoetapowy", "Program lojalnościowy", "Dashboard sprzedaży"],
    status: "demo" as const,
    featured: true,
    thumbnailUrl: null,
    demoUrl: null,
    technologies: ["React", "Node.js", "Stripe", "PostgreSQL"],
    sortOrder: "19",
  },
  {
    id: "52977ed8-7b2b-47b2-bcbc-3ca0534cf248",
    name: "AI Business Assistant — Chatbot + Lead Scoring",
    category: "AI",
    industry: "Business",
    description: "Inteligentny asystent biznesowy z AI. Chatbot kwalifikuje leady, odpowiada na pytania klientów 24/7 i automatyzuje procesy sprzedażowe.",
    features: ["Chatbot AI sprzedażowy", "Automatyczny lead scoring", "Integracja z CRM", "Analityka rozmów", "Wielojęzyczność"],
    status: "demo" as const,
    featured: true,
    thumbnailUrl: null,
    demoUrl: null,
    technologies: ["React", "Node.js", "OpenAI API", "PostgreSQL"],
    sortOrder: "20",
  },
];

export async function seedProjects() {
  const existing = await db.select().from(projectsTable);
  if (existing.length > 0) {
    console.log(`Projects already seeded (${existing.length} found). Skipping.`);
    return;
  }

  await db.insert(projectsTable).values(DEMO_PROJECTS);
  console.log(`Seeded ${DEMO_PROJECTS.length} demo projects.`);
}
